import { DateTime } from 'luxon'

const defaultEventDate = () => {
  const now = DateTime.local().setZone('America/Chicago')
  return now
    .plus({ months: 1 })
    .set({ day: 1 })
    .toLocaleString(DateTime.DATETIME_FULL)
}

const MEETUP_RESULTS = {
  message: 'success',
  response: {
    city: {
      id: 60601,
      city: 'Chicago',
      lat: 41.88,
      lon: -87.62,
      state: 'IL',
      country: 'us',
      zip: '60290',
      member_count: 90918,
    },
    events: [
      {
        created: 1548618452000,
        duration: 10800000,
        fee: {
          accepts: 'wepay',
          amount: 30,
          currency: 'USD',
          description: '',
          label: 'Price',
          required: true,
        },
        id: '258446391',
        name: 'The WTF Lounge',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1565217000000,
        local_date: '2019-08-07',
        local_time: '17:30',
        updated: 1549579255000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 1,
        venue: {
          id: 26119551,
          name: 'Merchandise Mart',
          lat: 41.88897705078125,
          lon: -87.63397979736328,
          repinned: true,
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60654',
          state: 'IL',
        },
        group: {
          created: 1456493474000,
          name: 'Women Tech Founders (WTF)',
          id: 19628554,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'Women-Tech-Founders-WTF-of-Chicago',
          who: 'Women Tech Founders (WTF)',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Women-Tech-Founders-WTF-of-Chicago/events/258446391/',
        description:
          "<p>Join today and tomorrow's innovators, tech entrepreneurs, leaders, investors, and changemakers. Be a part of our monthly Lounge, connect with the community, and rise with us.</p> <p>Member discounts: WomenTechFounders.com/Join/</p> <p>Agenda:<br/>5:30 pm Networking<br/>6:00 pm Welcome, introductions &amp; announcements<br/>6:30 pm Interview with award-winning founder<br/>7:00 pm Q &amp; A<br/>7:15 pm Breakouts<br/>8:00 pm Close</p> ",
        visibility: 'public',
      },
      {
        created: 1556753841000,
        duration: 5400000,
        id: '261088301',
        name: 'Women In Tech Breakfast (FREE) ',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1559307600000,
        local_date: '2019-05-31',
        local_time: '08:00',
        updated: 1556753854000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 13,
        venue: {
          id: 26313820,
          name: 'GA Chicago @ TechNexus   ',
          lat: 41.882530212402344,
          lon: -87.63748931884766,
          repinned: false,
          address_1: '20 N. Upper Wacker Drive, 12th Floor',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60606',
          state: 'il',
        },
        group: {
          created: 1413252782000,
          name: 'Chicago Startup Community',
          id: 17606542,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'Chicago-Startup-Community',
          who: 'Creators',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Startup-Community/events/261088301/',
        description:
          '<p>To reserve your spot to this event, you must RSVP on GA’s website here: <a href="https://generalassemb.ly/education/women-in-tech-breakfast/chicago/73066" class="linkified">https://generalassemb.ly/education/women-in-tech-breakfast/chicago/73066</a></p> <p>We invite you to join us for this interactive breakfast for Women in Technology &amp; Entrepreneurship. We featuring great women in tech to give their insight on how they reached their level of success, advice on navigating the workplace, and how we can help the next generation of women in tech. This dynamic panel will be moderated by Tricia Whitlock of Tech Square Labs, a new innovation hub for entrepreneurs.</p> <p>Our esteemed panel of speakers are pioneers in their respective fields, representing many facets of the international tech industry.</p> <p>After the panel, we will break into groups and take a deeper dive into the issues women face in the tech industry and find solutions to how we can rise above the obstacles and thrive in this growing field.</p> ',
        visibility: 'public',
      },
      {
        created: 1557862067000,
        duration: 7200000,
        id: '261458399',
        name:
          'Feeding the Influencer: Driving Food & Beverage Sales with Influencer Marketing',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561071600000,
        local_date: '2019-06-20',
        local_time: '18:00',
        updated: 1557862067000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 3,
        venue: {
          id: 26337759,
          name: 'The Hatchery Chicago',
          lat: 41.883888244628906,
          lon: -87.7058334350586,
          repinned: false,
          address_1: '135 N Kedzie Ave',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60612',
          state: 'IL',
        },
        group: {
          created: 1413252782000,
          name: 'Chicago Startup Community',
          id: 17606542,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'Chicago-Startup-Community',
          who: 'Creators',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Startup-Community/events/261458399/',
        description:
          '<p>To register for this free event: <a href="https://generalassemb.ly/education/feeding-the-influencer-driving-food-beverage-sales-with-influencer-marketing/chicago/78698" class="linkified">https://generalassemb.ly/education/feeding-the-influencer-driving-food-beverage-sales-with-influencer-marketing/chicago/78698</a></p> <p>Home to food tech incubators, a strong food entrepreneurship scene, and many multi-national consumer product goods (CPG) companies it\'s no wonder Chicago is one of the best (if not the best) city for food entrepreneurship. To create a thriving food startup, consumers need to discover your brand. With many of us spending hours a day on social media, influencers are a natural fit to help a business drive sales.</p> <p>This panel discussion will feature Influencers working with consumer product goods companies to shed some light on the world of influencer marketing. How does one become an influencer? Side hustle or full-time career? How does a brand identify the correct influencer and what does fair compensation look like? How do you measure the success of the partnership?</p> <p>Join General Assembly and the Hatchery for an exclusive event on the in\'s and out\'s of influencer marketing.</p> ',
        visibility: 'public',
      },
      {
        created: 1534509995000,
        duration: 9000000,
        id: 'wjnfcqyzhbmc',
        name: 'Chicago Sports-Tech Meetup - Happy Hour',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1559167200000,
        local_date: '2019-05-29',
        local_time: '17:00',
        updated: 1534509995000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 9,
        venue: {
          id: 25839646,
          name: 'Ballast Point Brewing Chicago',
          lat: 41.88616943359375,
          lon: -87.64893341064453,
          repinned: false,
          address_1: '212 N Green St',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60607',
          state: 'il',
        },
        group: {
          created: 1414766117000,
          name: 'Chicago Sports-Tech Meetup',
          id: 17984362,
          join_mode: 'open',
          lat: 41.939998626708984,
          lon: -87.75,
          urlname: 'Chicago-Sports-Tech-Meetup',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Sports-Tech-Meetup/events/wjnfcqyzhbmc/',
        description:
          "<p>Come network with industry professionals and enjoy a few drinks. It's a great opportunity to learn what's going on in the industry and share new ideas.</p> ",
        how_to_find_us: 'We will have a couple tables at Ballast Point. ',
        visibility: 'public',
      },
      {
        created: 1534509995000,
        duration: 9000000,
        id: 'wjnfcqyzjbjc',
        name: 'Chicago Sports-Tech Meetup - Happy Hour',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561586400000,
        local_date: '2019-06-26',
        local_time: '17:00',
        updated: 1534509995000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 5,
        venue: {
          id: 25839646,
          name: 'Ballast Point Brewing Chicago',
          lat: 41.88616943359375,
          lon: -87.64893341064453,
          repinned: false,
          address_1: '212 N Green St',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60607',
          state: 'il',
        },
        group: {
          created: 1414766117000,
          name: 'Chicago Sports-Tech Meetup',
          id: 17984362,
          join_mode: 'open',
          lat: 41.939998626708984,
          lon: -87.75,
          urlname: 'Chicago-Sports-Tech-Meetup',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Sports-Tech-Meetup/events/wjnfcqyzjbjc/',
        description:
          "<p>Come network with industry professionals and enjoy a few drinks. It's a great opportunity to learn what's going on in the industry and share new ideas.</p> ",
        how_to_find_us: 'We will have a couple tables at Ballast Point. ',
        visibility: 'public',
      },
      {
        created: 1534509995000,
        duration: 9000000,
        id: 'wjnfcqyzkbpc',
        name: 'Chicago Sports-Tech Meetup - Happy Hour',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1564610400000,
        local_date: '2019-07-31',
        local_time: '17:00',
        updated: 1534509995000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 3,
        venue: {
          id: 25839646,
          name: 'Ballast Point Brewing Chicago',
          lat: 41.88616943359375,
          lon: -87.64893341064453,
          repinned: false,
          address_1: '212 N Green St',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60607',
          state: 'il',
        },
        group: {
          created: 1414766117000,
          name: 'Chicago Sports-Tech Meetup',
          id: 17984362,
          join_mode: 'open',
          lat: 41.939998626708984,
          lon: -87.75,
          urlname: 'Chicago-Sports-Tech-Meetup',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Sports-Tech-Meetup/events/wjnfcqyzkbpc/',
        description:
          "<p>Come network with industry professionals and enjoy a few drinks. It's a great opportunity to learn what's going on in the industry and share new ideas.</p> ",
        how_to_find_us: 'We will have a couple tables at Ballast Point. ',
        visibility: 'public',
      },
      {
        created: 1555431023000,
        duration: 7200000,
        id: '260672837',
        name:
          'Top Five Mistakes Startups Make with Their Innovations (and how to avoid them)',
        rsvp_limit: 30,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1559147400000,
        local_date: '2019-05-29',
        local_time: '11:30',
        updated: 1555431050000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 30,
        venue: {
          id: 25426868,
          name: '36 squared',
          lat: 41.827449798583984,
          lon: -87.65990447998047,
          repinned: true,
          address_1: '3636 South Iron Street',
          city: 'Chicago',
          country: 'US',
          localized_country_name: 'USA',
        },
        group: {
          created: 1247643623000,
          name: 'Chicago Lean Startup Circle',
          id: 1489965,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'ChicagoLeanStartup',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link: 'https://www.meetup.com/ChicagoLeanStartup/events/260672837/',
        description:
          '<p>Attorney Randy Micheletti from IncubateIP will discuss methods of protecting your intellectual property and common mistakes that might make your business vulnerable. Doors open for networking and registration at 11:30 am with the presentation starting promptly at noon.</p> <p>A light lunch and beverages will be served. This event is FREE thanks to our sponsors at CIBC and the Greater Southwest Development Corporation.</p> ',
        visibility: 'public',
      },
      {
        created: 1556396667000,
        duration: 10800000,
        id: '260975599',
        name: "Networking at the South Loop's New Hidden Gem - VU Rooftop!",
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1562713200000,
        local_date: '2019-07-09',
        local_time: '18:00',
        updated: 1556396667000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 6,
        venue: {
          id: 26121474,
          name: 'VU Rooftop Bar',
          lat: 41.852745056152344,
          lon: -87.62277221679688,
          repinned: false,
          address_1: '133 E Cermak Rd',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60616',
          state: 'IL',
        },
        group: {
          created: 1358727648000,
          name: 'Chicago Tech Happy Hour',
          id: 6756852,
          join_mode: 'open',
          lat: 41.900001525878906,
          lon: -87.63999938964844,
          urlname: 'Chicago-Tech-Happy-Hour',
          who: 'Techies',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Tech-Happy-Hour/events/260975599/',
        description:
          '<p>The VU, the name says it all! Twenty-two stories above the street, and across from Wintrust, the VU is roomy with two outdoor patios sporting unparalleled views of the city and lake, three bars and fire pits throughout. Ambiance is cool, but not pretentious and drinks are strong and well made. The South Loop finally has a nice, sexy rooftop, a real must see on everyone’s bucket list! There is not a better place to be in Chicago on a summer night. The view is swanky, and the people are classy, so dress to impress.</p> <p>Join us and you will network with other top level people who share your interests. There will be potential clients, employers, employees, partners, contacts and just the nicest people you could meet anywhere.</p> <p>Tickets are available online starting at $12 at: <a href="https://www.eventbrite.com/e/network-at-the-south-loops-new-hidden-gem-the-vu-rooftop-tickets-60673400775" class="linkified">https://www.eventbrite.com/e/network-at-the-south-loops-new-hidden-gem-the-vu-rooftop-tickets-60673400775</a>. Please get your tickets early as prices will go up as tickets are sold.</p> <p>Tickets include:</p> <p>A drink ticket<br/>Free door prize raffle<br/>Color coded name tags<br/>Free massages from Fitlifegive<br/>An awesome view from Chicago’s hottest new rooftop<br/>The best networking in the City</p> ',
        visibility: 'public',
      },
      {
        created: 1554219758000,
        duration: 5400000,
        id: '260279808',
        name: 'Intro to JavaScript: Build a Guessing Game',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1559086200000,
        local_date: '2019-05-28',
        local_time: '18:30',
        updated: 1554219758000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 5,
        venue: {
          id: 26192290,
          name: 'MakeOffices at River North',
          lat: 41.8887825012207,
          lon: -87.63787078857422,
          repinned: false,
          address_1: '350 N Orleans St #9000n',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60654',
          state: 'IL',
        },
        group: {
          created: 1386185186000,
          name: 'Learn to Code in Chicago',
          id: 11343122,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'TK-Learn-To-Code-Chicago',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/TK-Learn-To-Code-Chicago/events/260279808/',
        description:
          '<p>*** Please RSVP on Eventbrite: <a href="https://www.eventbrite.com/e/intro-to-javascript-build-a-guessing-game-tickets-59774950486?aff=Meetup" class="linkified">https://www.eventbrite.com/e/intro-to-javascript-build-a-guessing-game-tickets-59774950486?aff=Meetup</a> ***</p> <p>Looking for a fun way to learn to code? Join us as we teach you how to build a simple guessing game while learning the fundamentals of JavaScript, the most popular programming language.</p> <p>With each new JavaScript concept you learn, you will add new features to the game, including keeping track of how many guesses you\'ve had and starting a new game from scratch.</p> <p>Suggested Experience Level:<br/>Beginner - no previous coding experience needed</p> <p>What to Bring:<br/>Laptop - this will ensure you get the most out of this workshop<br/>Water bottle</p> <p>How to find us: MakeOffice River North<br/>The event will be held at MakeOffice River Loop located at 350 W. Wolf Point Plaza. For the easiest access, enter the Holiday Inn Wolf Point entrance. Once in the building, speak with security at the front desk letting them know you\'re here for the ""Thinkful Workshop."" Take the elevators to the 9th floor and go to your left, here you will find MakeOffices. SpotHero is the best parking app to use to get into the nearest spots for cheap rates. MakeOffices is also located nearest to the Merchandise Mart stop.</p> <p>If event is sold out, please contact Community Manager: Caitlin ([masked])</p> <p>Sponsored by Thinkful:<br/>This workshop is proudly sponsored by Thinkful, the #1 rated coding boot camp on CourseReport. Thinkful is a new type of school that brings high-growth tech careers to ambitious people everywhere. Thinkful provides 1-on-1 learning through its network of industry experts, hiring partners, and online platform to deliver a structured and flexible education. To join the Thinkful network, visit thinkful.com.</p> ',
        visibility: 'public',
        pro_is_email_shared: false,
      },
      {
        created: 1554220226000,
        duration: 5400000,
        id: '260279978',
        name: 'Intro to Data Science: The Art of Visualizations',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1559172600000,
        local_date: '2019-05-29',
        local_time: '18:30',
        updated: 1554220226000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 5,
        venue: {
          id: 26192290,
          name: 'MakeOffices at River North',
          lat: 41.8887825012207,
          lon: -87.63787078857422,
          repinned: false,
          address_1: '350 N Orleans St #9000n',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60654',
          state: 'IL',
        },
        group: {
          created: 1386185186000,
          name: 'Learn to Code in Chicago',
          id: 11343122,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'TK-Learn-To-Code-Chicago',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/TK-Learn-To-Code-Chicago/events/260279978/',
        description:
          '<p>*** Please RSVP on Eventbrite: <a href="https://www.eventbrite.com/e/intro-to-data-science-the-art-of-visualizations-tickets-59775280473?aff=meetup" class="linkified">https://www.eventbrite.com/e/intro-to-data-science-the-art-of-visualizations-tickets-59775280473?aff=meetup</a> ***</p> <p>The beauty behind the data...visualizations. In a data science career, you need more than the ability to process a large amount of data, you need to be able to communicate your findings to the right audience. You need the beauty behind the data...you need visualizations!</p> <p>Visualizations help you understand your data, and most importantly, they help you communicate your data. In this hands-on workshop, we’ll discuss the different visualization packages in Python, and walk through how to implement them while covering some key data science concepts.</p> <p>Suggested Experience Level:<br/>Beginner - some prior programming experience is helpful</p> <p>What to Bring:<br/>Laptop - this will ensure you get the most out of this workshop<br/>Water bottle</p> <p>How to find us: MakeOffice River North<br/>The event will be held at MakeOffice River Loop located at 350 W. Wolf Point Plaza. For the easiest access, enter the Holiday Inn Wolf Point entrance. Once in the building, speak with security at the front desk letting them know you\'re here for the ""Thinkful Workshop."" Take the elevators to the 9th floor and go to your left, here you will find MakeOffices. SpotHero is the best parking app to use to get into the nearest spots for cheap rates. MakeOffices is also located nearest to the Merchandise Mart stop.</p> <p>If event is sold out, please contact Community Manager: Caitlin ([masked])</p> <p>Sponsored by Thinkful:<br/>This workshop is proudly sponsored by Thinkful, the #1 rated coding boot camp on CourseReport. Thinkful is a new type of school that brings high-growth tech careers to ambitious people everywhere. Thinkful provides 1-on-1 learning through its network of industry experts, hiring partners, and online platform to deliver a structured and flexible education. To join the Thinkful network, visit thinkful.com.</p> ',
        visibility: 'public',
        pro_is_email_shared: false,
      },
      {
        created: 1555700450000,
        duration: 10800000,
        id: '260765633',
        name: 'AD Recovery Services - Sign Up Now!',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1560528000000,
        local_date: '2019-06-14',
        local_time: '11:00',
        updated: 1557406175000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 1,
        venue: {
          id: 26176867,
          name: 'Microsoft Midwest District',
          lat: 41.885284423828125,
          lon: -87.62151336669922,
          repinned: true,
          address_1: '200 E Randolph St #200',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60601',
          state: 'IL',
        },
        group: {
          created: 1550071875000,
          name: 'Microsoft Tech Talks - Chicago',
          id: 31156470,
          join_mode: 'open',
          lat: 41.880001068115234,
          lon: -87.62000274658203,
          urlname: 'MTTChicago',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link: 'https://www.meetup.com/MTTChicago/events/260765633/',
        description:
          '<p>***signup will be through the MS Events page link below, not Meetup***</p> <p>SIGNUP NOW! <a href="https://aka.ms/CHITechTalks" class="linkified">https://aka.ms/CHITechTalks</a><br/>We will be talking about how to build out and maintain your AD Recovery procedure. Now is the time to ask an expert about where you should be in your AD DR planning</p> ',
        visibility: 'public',
      },
      {
        created: 1556812929000,
        duration: 5400000,
        id: '261107884',
        name: 'Intro to HTML/CSS: Build Your Own Website',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1559691000000,
        local_date: '2019-06-04',
        local_time: '18:30',
        updated: 1556812929000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 8,
        venue: {
          id: 26192290,
          name: 'MakeOffices at River North',
          lat: 41.8887825012207,
          lon: -87.63787078857422,
          repinned: false,
          address_1: '350 N Orleans St #9000n',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60654',
          state: 'IL',
        },
        group: {
          created: 1386185186000,
          name: 'Learn to Code in Chicago',
          id: 11343122,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'TK-Learn-To-Code-Chicago',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/TK-Learn-To-Code-Chicago/events/261107884/',
        description:
          '<p>***Please RSVP on Eventbrite: <a href="https://www.eventbrite.com/e/intro-to-htmlcss-build-your-own-website-tickets-61242161955?aff=Meetup" class="linkified">https://www.eventbrite.com/e/intro-to-htmlcss-build-your-own-website-tickets-61242161955?aff=Meetup</a> ***</p> <p>Curious about coding, but don’t know where to begin? This workshop is the perfect place to start. Join us as we teach you the fundamentals of HTML &amp; CSS while building an interactive website.<br/>In this workshop, you\'ll learn the key concepts of HTML &amp; CSS, which are the basic “building blocks” of all websites. You\'ll start building your own site with the help of our instructor and TAs, and you’ll leave with your own site live on the internet to share with your friends and family. Take a look at a live website created by a previous attendee here! <a href="https://ludicrous-mailbox.glitch.me/" class="linkified">https://ludicrous-mailbox.glitch.me/</a></p> <p>Suggested Experience Level:<br/>Beginner - no previous coding experience needed</p> <p>What to Bring:<br/>Laptop - this will ensure you get the most out of this workshop<br/>Water bottle</p> <p>How to find us: The event will be held at MakeOffice River Loop located at 350 W. Wolf Point Plaza. For the easiest access, enter the Holiday Inn Wolf Point entrance. Once in the building, speak with security at the front desk letting them know you\'re here for the ""Thinkful Workshop."" Take the elevators to the 9th floor and go to your left, here you will find MakeOffices. SpotHero is the best parking app to use to get into the nearest spots for cheap rates. MakeOffices is also located nearest to the Merchandise Mart stop.</p> <p>If event is sold out, please contact Community Manager: Caitlin ([masked])</p> <p>Sponsored by Thinkful:<br/>This workshop is proudly sponsored by Thinkful, the #1 rated coding boot camp on CourseReport. Thinkful specializes in high-growth tech careers and provides 1-on-1 learning through its network of industry experts, hiring partners, and online platform to deliver a structured and flexible education. To join the Thinkful network, visit thinkful.com.</p> <p>Can\'t make it in person? Join one of our webinars: www.thinkful.com/webinars</p> ',
        visibility: 'public',
        pro_is_email_shared: false,
      },
      {
        created: 1556813223000,
        duration: 5400000,
        id: '261107960',
        name: 'Intro to Python: Fundamentals',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1559777400000,
        local_date: '2019-06-05',
        local_time: '18:30',
        updated: 1556813223000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 4,
        venue: {
          id: 26192290,
          name: 'MakeOffices at River North',
          lat: 41.8887825012207,
          lon: -87.63787078857422,
          repinned: false,
          address_1: '350 N Orleans St #9000n',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60654',
          state: 'IL',
        },
        group: {
          created: 1386185186000,
          name: 'Learn to Code in Chicago',
          id: 11343122,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'TK-Learn-To-Code-Chicago',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/TK-Learn-To-Code-Chicago/events/261107960/',
        description:
          '<p>*** Please RSVP on Eventbrite: <a href="https://www.eventbrite.com/e/intro-to-python-fundamentals-tickets-61242442795?aff=meetup" class="linkified">https://www.eventbrite.com/e/intro-to-python-fundamentals-tickets-61242442795?aff=meetup</a> ***</p> <p>Curious what Python is all about? Are you data-driven and interested in finding out how Python can take you to the next level? Join us for this hands-on workshop while we explore variables, data structures, functions, and go over basic data science concepts.</p> <p>Suggested Experience Level:<br/>Beginner - no prior programming experience is needed</p> <p>What to Bring:<br/>Laptop - this will ensure you get the most out of this workshop<br/>Water bottle</p> <p>How to find us: The event will be held at MakeOffice River Loop located at 350 W. Wolf Point Plaza. For the easiest access, enter the Holiday Inn Wolf Point entrance. Once in the building, speak with security at the front desk letting them know you\'re here for the ""Thinkful Workshop."" Take the elevators to the 9th floor and go to your left, here you will find MakeOffices. SpotHero is the best parking app to use to get into the nearest spots for cheap rates. MakeOffices is also located nearest to the Merchandise Mart stop.</p> <p>If event is sold out, please contact Community Manager: Caitlin ([masked])</p> <p>Sponsored by Thinkful:<br/>This workshop is proudly sponsored by Thinkful, the #1 rated coding boot camp on CourseReport. Thinkful specializes in high-growth tech careers and provides 1-on-1 learning through its network of industry experts, hiring partners, and online platform to deliver a structured and flexible education. To join the Thinkful network, visit thinkful.com.</p> <p>Can\'t make it in person? Join one of our webinars: www.thinkful.com/webinars</p> ',
        visibility: 'public',
        pro_is_email_shared: false,
      },
      {
        created: 1556813407000,
        duration: 5400000,
        id: '261108013',
        name: 'Intro to Git & GitHub: Your Coding Safety Net',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1560295800000,
        local_date: '2019-06-11',
        local_time: '18:30',
        updated: 1556813407000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 7,
        venue: {
          id: 26192290,
          name: 'MakeOffices at River North',
          lat: 41.8887825012207,
          lon: -87.63787078857422,
          repinned: false,
          address_1: '350 N Orleans St #9000n',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60654',
          state: 'IL',
        },
        group: {
          created: 1386185186000,
          name: 'Learn to Code in Chicago',
          id: 11343122,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'TK-Learn-To-Code-Chicago',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/TK-Learn-To-Code-Chicago/events/261108013/',
        description:
          '<p>*** Please RSVP on Eventbrite: <a href="https://www.eventbrite.com/e/intro-to-git-github-your-coding-safety-net-tickets-61242841989?aff=meetup" class="linkified">https://www.eventbrite.com/e/intro-to-git-github-your-coding-safety-net-tickets-61242841989?aff=meetup</a> ***</p> <p>Ever said something you wish you could take back? Well, Git is your coding time machine. Mistakes in your code are inevitable. Join us to learn how Git allows you to roll back to when our code was still working and avoid making the same mistake twice. It is truly your coding safety net.</p> <p>Suggested Experience Level:<br/>Beginner - some coding experience will be helpful</p> <p>What to Bring:<br/>Laptop - this will ensure you get the most out of this workshop<br/>Water bottle</p> <p>How to find us: The event will be held at MakeOffice River Loop located at 350 W. Wolf Point Plaza. For the easiest access, enter the Holiday Inn Wolf Point entrance. Once in the building, speak with security at the front desk letting them know you\'re here for the ""Thinkful Workshop."" Take the elevators to the 9th floor and go to your left, here you will find MakeOffices. SpotHero is the best parking app to use to get into the nearest spots for cheap rates. MakeOffices is also located nearest to the Merchandise Mart stop.</p> <p>If event is sold out, please contact Community Manager: Caitlin ([masked])</p> <p>Sponsored by Thinkful:<br/>This workshop is proudly sponsored by Thinkful, the #1 rated coding boot camp on CourseReport. Thinkful specializes in high-growth tech careers and provides 1-on-1 learning through its network of industry experts, hiring partners, and online platform to deliver a structured and flexible education. To join the Thinkful network, visit thinkful.com.</p> <p>Can\'t make it in person? Join one of our webinars: www.thinkful.com/webinars</p> ',
        visibility: 'public',
        pro_is_email_shared: false,
      },
      {
        created: 1556813975000,
        duration: 5400000,
        id: '261108197',
        name: 'Intro to Data Science: Build a Predictive Model',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1560382200000,
        local_date: '2019-06-12',
        local_time: '18:30',
        updated: 1556813975000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 2,
        venue: {
          id: 26192290,
          name: 'MakeOffices at River North',
          lat: 41.8887825012207,
          lon: -87.63787078857422,
          repinned: false,
          address_1: '350 N Orleans St #9000n',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60654',
          state: 'IL',
        },
        group: {
          created: 1386185186000,
          name: 'Learn to Code in Chicago',
          id: 11343122,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'TK-Learn-To-Code-Chicago',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/TK-Learn-To-Code-Chicago/events/261108197/',
        description:
          '<p>*** Please RSVP on Eventbrite: <a href="https://www.eventbrite.com/e/intro-to-data-science-build-a-predictive-model-tickets-61243678491?aff=Meetup" class="linkified">https://www.eventbrite.com/e/intro-to-data-science-build-a-predictive-model-tickets-61243678491?aff=Meetup</a> ***</p> <p>If you\'re curious about Data Science, then Python is the language to learn. In this interactive workshop, you\'ll learn the fundamentals of Python by building a predictive model from scratch, training the model and running predictions against it. We\'ll cover everything you need to know to start learning the language, as well as introduce core Data Science concepts and processes.</p> <p>Suggested Experience Level:<br/>Intermediate - no previous coding knowledge is required, though some experience with data is a plus</p> <p>What to Bring:<br/>Laptop - this will ensure you get the most out of this workshop<br/>Water bottle</p> <p>How to find us: The event will be held at MakeOffice River Loop located at 350 W. Wolf Point Plaza. For the easiest access, enter the Holiday Inn Wolf Point entrance. Once in the building, speak with security at the front desk letting them know you\'re here for the ""Thinkful Workshop."" Take the elevators to the 9th floor and go to your left, here you will find MakeOffices. SpotHero is the best parking app to use to get into the nearest spots for cheap rates. MakeOffices is also located nearest to the Merchandise Mart stop.</p> <p>If event is sold out, please contact Community Manager: Caitlin ([masked])</p> <p>Sponsored by Thinkful:<br/>This workshop is proudly sponsored by Thinkful, the #1 rated coding boot camp on CourseReport. Thinkful specializes in high-growth tech careers and provides 1-on-1 learning through its network of industry experts, hiring partners, and online platform to deliver a structured and flexible education. To join the Thinkful network, visit thinkful.com.</p> <p>Can\'t make it in person? Join one of our webinars: www.thinkful.com/webinars</p> ',
        visibility: 'public',
        pro_is_email_shared: false,
      },
      {
        created: 1556814151000,
        duration: 5400000,
        id: '261108234',
        name: 'Intro to JavaScript: Build a Virtual Pet',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1560900600000,
        local_date: '2019-06-18',
        local_time: '18:30',
        updated: 1556814151000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 3,
        venue: {
          id: 26192290,
          name: 'MakeOffices at River North',
          lat: 41.8887825012207,
          lon: -87.63787078857422,
          repinned: false,
          address_1: '350 N Orleans St #9000n',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60654',
          state: 'IL',
        },
        group: {
          created: 1386185186000,
          name: 'Learn to Code in Chicago',
          id: 11343122,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'TK-Learn-To-Code-Chicago',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/TK-Learn-To-Code-Chicago/events/261108234/',
        description:
          '<p>*** Please RSVP on Eventbrite: <a href="https://www.eventbrite.com/e/intro-to-javascript-build-a-virtual-pet-tickets-61244173973?aff=Meetup" class="linkified">https://www.eventbrite.com/e/intro-to-javascript-build-a-virtual-pet-tickets-61244173973?aff=Meetup</a> ***</p> <p>Curious about JavaScript? Join us and learn the fundamental concepts of JavaScript while building your own virtual pet! (Think: Tamagotchi)</p> <p>You will learn how to add new features to your pet, including feeding them, and tracking their health and happiness. Check out this example of a virtual pet that was made by an attendee at a previous event: <a href="https://cumbersome-vole.glitch.me/" class="linkified">https://cumbersome-vole.glitch.me/</a></p> <p>Suggested Experience Level:<br/>Beginner - no previous coding experience needed</p> <p>What to Bring:<br/>Laptop - this will ensure you get the most out of this workshop<br/>Water bottle</p> <p>How to find us: The event will be held at MakeOffice River Loop located at 350 W. Wolf Point Plaza. For the easiest access, enter the Holiday Inn Wolf Point entrance. Once in the building, speak with security at the front desk letting them know you\'re here for the ""Thinkful Workshop."" Take the elevators to the 9th floor and go to your left, here you will find MakeOffices. SpotHero is the best parking app to use to get into the nearest spots for cheap rates. MakeOffices is also located nearest to the Merchandise Mart stop.</p> <p>If event is sold out, please contact Community Manager: Caitlin ([masked])</p> <p>Sponsored by Thinkful:<br/>This workshop is proudly sponsored by Thinkful, the #1 rated coding boot camp on CourseReport. Thinkful specializes in high-growth tech careers and provides 1-on-1 learning through its network of industry experts, hiring partners, and online platform to deliver a structured and flexible education. To join the Thinkful network, visit thinkful.com.</p> <p>Can\'t make it in person? Join one of our webinars: www.thinkful.com/webinars</p> ',
        visibility: 'public',
        pro_is_email_shared: false,
      },
      {
        created: 1556816561000,
        duration: 5400000,
        id: '261109528',
        name: 'Intro to Data Science: The Art of Visualizations',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1560987000000,
        local_date: '2019-06-19',
        local_time: '18:30',
        updated: 1556816561000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 2,
        venue: {
          id: 26192290,
          name: 'MakeOffices at River North',
          lat: 41.8887825012207,
          lon: -87.63787078857422,
          repinned: false,
          address_1: '350 N Orleans St #9000n',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60654',
          state: 'IL',
        },
        group: {
          created: 1386185186000,
          name: 'Learn to Code in Chicago',
          id: 11343122,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'TK-Learn-To-Code-Chicago',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/TK-Learn-To-Code-Chicago/events/261109528/',
        description:
          '<p>*** Please RSVP on Eventbrite: <a href="https://www.eventbrite.com/e/intro-to-data-science-the-art-of-visualizations-tickets-61244320411?aff=meetup" class="linkified">https://www.eventbrite.com/e/intro-to-data-science-the-art-of-visualizations-tickets-61244320411?aff=meetup</a> ***</p> <p>The beauty behind the data...visualizations. In a data science career, you need more than the ability to process a large amount of data, you need to be able to communicate your findings to the right audience. You need the beauty behind the data...you need visualizations!</p> <p>Visualizations help you understand your data, and most importantly, they help you communicate your data. In this hands-on workshop, we’ll discuss the different visualization packages in Python, and walk through how to implement them while covering some key data science concepts.</p> <p>Suggested Experience Level:<br/>Beginner - some prior programming experience is helpful</p> <p>What to Bring:<br/>Laptop - this will ensure you get the most out of this workshop<br/>Water bottle</p> <p>How to find us: The event will be held at MakeOffice River Loop located at 350 W. Wolf Point Plaza. For the easiest access, enter the Holiday Inn Wolf Point entrance. Once in the building, speak with security at the front desk letting them know you\'re here for the ""Thinkful Workshop."" Take the elevators to the 9th floor and go to your left, here you will find MakeOffices. SpotHero is the best parking app to use to get into the nearest spots for cheap rates. MakeOffices is also located nearest to the Merchandise Mart stop.</p> <p>If event is sold out, please contact Community Manager: Caitlin ([masked])</p> <p>Sponsored by Thinkful:<br/>This workshop is proudly sponsored by Thinkful, the #1 rated coding boot camp on CourseReport. Thinkful specializes in high-growth tech careers and provides 1-on-1 learning through its network of industry experts, hiring partners, and online platform to deliver a structured and flexible education. To join the Thinkful network, visit thinkful.com.</p> <p>Can\'t make it in person? Join one of our webinars: www.thinkful.com/webinars</p> ',
        visibility: 'public',
        pro_is_email_shared: false,
      },
      {
        created: 1556816741000,
        duration: 5400000,
        id: '261109587',
        name: 'Free Crash Course | Build a Web App with JavaScript & jQuery',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561505400000,
        local_date: '2019-06-25',
        local_time: '18:30',
        updated: 1556816741000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 7,
        venue: {
          id: 26192290,
          name: 'MakeOffices at River North',
          lat: 41.8887825012207,
          lon: -87.63787078857422,
          repinned: false,
          address_1: '350 N Orleans St #9000n',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60654',
          state: 'IL',
        },
        group: {
          created: 1386185186000,
          name: 'Learn to Code in Chicago',
          id: 11343122,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'TK-Learn-To-Code-Chicago',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/TK-Learn-To-Code-Chicago/events/261109587/',
        description:
          '<p>*** Please RSVP on Eventbrite: <a href="https://www.eventbrite.com/e/free-crash-course-build-a-web-app-with-javascript-jquery-tickets-61247177958?aff=meetup" class="linkified">https://www.eventbrite.com/e/free-crash-course-build-a-web-app-with-javascript-jquery-tickets-61247177958?aff=meetup</a> ***</p> <p>JavaScript is the language of the browser. Every website you\'ve ever used is built with JavaScript, with interaction powered by the popular jQuery library. Learn how to use JavaScript and jQuery and build a simple web app in this workshop.</p> <p>Together we\'ll learn key jQuery concepts like manipulating the DOM and using event listeners to update our app in real time. Here is an example of a web app that was made by an attendee at one of our previous events: <a href="https://unique-heart.glitch.me/" class="linkified">https://unique-heart.glitch.me/</a></p> <p>Suggested Experience Level:<br/>Intermediate - previous experience with JavaScript a plus</p> <p>What to Bring:<br/>Laptop - this will ensure you get the most out of this workshop<br/>Water bottle</p> <p>How to find us: The event will be held at MakeOffice River Loop located at 350 W. Wolf Point Plaza. For the easiest access, enter the Holiday Inn Wolf Point entrance. Once in the building, speak with security at the front desk letting them know you\'re here for the ""Thinkful Workshop."" Take the elevators to the 9th floor and go to your left, here you will find MakeOffices. SpotHero is the best parking app to use to get into the nearest spots for cheap rates. MakeOffices is also located nearest to the Merchandise Mart stop.</p> <p>If event is sold out, please contact Community Manager: Caitlin ([masked])</p> <p>Sponsored by Thinkful:<br/>This workshop is proudly sponsored by Thinkful, the #1 rated coding boot camp on CourseReport. Thinkful specializes in high-growth tech careers and provides 1-on-1 learning through its network of industry experts, hiring partners, and online platform to deliver a structured and flexible education. To join the Thinkful network, visit thinkful.com.</p> <p>Can\'t make it in person? Join one of our webinars: www.thinkful.com/webinars</p> ',
        visibility: 'public',
        pro_is_email_shared: false,
      },
      {
        created: 1556816938000,
        duration: 5400000,
        id: '261109646',
        name: 'Intro to Data Science: Plan Your Vacation',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561591800000,
        local_date: '2019-06-26',
        local_time: '18:30',
        updated: 1556816938000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 4,
        venue: {
          id: 26192290,
          name: 'MakeOffices at River North',
          lat: 41.8887825012207,
          lon: -87.63787078857422,
          repinned: false,
          address_1: '350 N Orleans St #9000n',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60654',
          state: 'IL',
        },
        group: {
          created: 1386185186000,
          name: 'Learn to Code in Chicago',
          id: 11343122,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'TK-Learn-To-Code-Chicago',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/TK-Learn-To-Code-Chicago/events/261109646/',
        description:
          '<p>*** Please RSVP on Eventbrite: <a href="https://www.eventbrite.com/e/intro-to-data-science-plan-your-vacation-tickets-61247306342?aff=meetup" class="linkified">https://www.eventbrite.com/e/intro-to-data-science-plan-your-vacation-tickets-61247306342?aff=meetup</a> ***</p> <p>Vacations are fun. Planning them is not. Data Science can help. In this practical workshop, you’ll use hotel reviews to build a predictive model to determine where you should take your next vacation. You’ll be introduced to basic Data Science tools and methods, including an overview of basic machine learning concepts.</p> <p>Suggested Experience Level:<br/>Intermediate - some programming background is helpful</p> <p>What to Bring:<br/>Laptop - this will ensure you get the most out of this workshop<br/>Water bottle</p> <p>How to find us: The event will be held at MakeOffice River Loop located at 350 W. Wolf Point Plaza. For the easiest access, enter the Holiday Inn Wolf Point entrance. Once in the building, speak with security at the front desk letting them know you\'re here for the ""Thinkful Workshop."" Take the elevators to the 9th floor and go to your left, here you will find MakeOffices. SpotHero is the best parking app to use to get into the nearest spots for cheap rates. MakeOffices is also located nearest to the Merchandise Mart stop.</p> <p>If event is sold out, please contact Community Manager: Caitlin ([masked])</p> <p>Sponsored by Thinkful:<br/>This workshop is proudly sponsored by Thinkful, the #1 rated coding boot camp on CourseReport. Thinkful specializes in high-growth tech careers and provides 1-on-1 learning through its network of industry experts, hiring partners, and online platform to deliver a structured and flexible education. To join the Thinkful network, visit thinkful.com.</p> <p>Can\'t make it in person? Join one of our webinars: www.thinkful.com/webinars</p> ',
        visibility: 'public',
        pro_is_email_shared: false,
      },
      {
        created: 1558028481000,
        duration: 7200000,
        id: '261516595',
        name: 'Pitch-prov - Improving your Pitch',
        rsvp_limit: 45,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561416000000,
        local_date: '2019-06-24',
        local_time: '17:40',
        rsvp_close_offset: 'PT72H',
        updated: 1558493468000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 9,
        venue: {
          id: 26025473,
          name: 'WeWork',
          lat: 41.89055633544922,
          lon: -87.63172149658203,
          repinned: true,
          address_1: '111 W Illinois St',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60654',
          state: 'IL',
        },
        group: {
          created: 1247643623000,
          name: 'Chicago Lean Startup Circle',
          id: 1489965,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'ChicagoLeanStartup',
          who: 'Members',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link: 'https://www.meetup.com/ChicagoLeanStartup/events/261516595/',
        description:
          "<p>Are you a founder or co-founder raising capital? Do you wonder if you Pitch is really selling your company? Are you open to testing your pitch and giving others feedback on their Pitches? Would you like to have fun doing both?</p> <p>Join us for Pitch-prov where we'll combine the best of pitch coaching and improv to help you understand what others hear when you pitch your company. Most of the evening will be spent in breakout groups where you'll take turns doing your elevator pitch then learning how other interpret it through improv.</p> <p>Our fearless leader for this evening of learning is Mary Cait Walthall. She teaches improv at IO Theater in addition to working with startups on communication and culture. Some of her students will join us to coach the breakout groups and keep things moving.</p> <p>Agenda</p> <p>5:45: Intros and the basic components of a pitch<br/>6:00: Break into groups and learn how the exercise works<br/>6:15 - 7:15: Work on your pitches in your groups<br/>7:15 - 7:30 Wrap up</p> ",
        how_to_find_us:
          "Please come go up to the 5th floor. We'll be in the common area.",
        visibility: 'public',
      },
      {
        created: 1553121691000,
        duration: 7200000,
        id: '259940391',
        name: 'Storytelling Hacks for Networking + Interviews ($35.00) ',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1559084400000,
        local_date: '2019-05-28',
        local_time: '18:00',
        updated: 1553121691000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 2,
        venue: {
          id: 25917182,
          name: 'General Assembly @ rent24',
          lat: 41.890647888183594,
          lon: -87.62683868408203,
          repinned: false,
          address_1: '444 N. Wabash Avenue, 5th Floor',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60611',
          state: 'il',
        },
        group: {
          created: 1413252782000,
          name: 'Chicago Startup Community',
          id: 17606542,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'Chicago-Startup-Community',
          who: 'Creators',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Startup-Community/events/259940391/',
        description:
          "<p>Tell me about yourself: the four words that strike fear in any career-related conversation.</p> <p>And we all know the best way to make a point or inspire action in the workplace is by telling a compelling story. And as it relates to work, we'll often see that struggling to describe who we are and what they do leads to missed opportunities for advancement.</p> <p>So we're bringing together career experts to share their tricks for how to break down your past experience and new skills and start talking about yourself in a comprehensive narrative.</p> ",
        how_to_find_us:
          'Red line at State and Grand.  1 block north and 1 block west of us.  (3 minute walk)\nBlue, Purple, Green, Pink/Brown, Orange lines at Clark & Lake (10 minute walk)',
        visibility: 'public',
      },
      {
        created: 1553124297000,
        duration: 10800000,
        id: '259941043',
        name: 'Content Strategy Masterclass ($60.00) ',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1558652400000,
        local_date: '2019-05-23',
        local_time: '18:00',
        updated: 1553124297000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 2,
        venue: {
          id: 25917182,
          name: 'General Assembly @ rent24',
          lat: 41.890647888183594,
          lon: -87.62683868408203,
          repinned: false,
          address_1: '444 N. Wabash Avenue, 5th Floor',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60611',
          state: 'il',
        },
        group: {
          created: 1413252782000,
          name: 'Chicago Startup Community',
          id: 17606542,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'Chicago-Startup-Community',
          who: 'Creators',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Startup-Community/events/259941043/',
        description:
          "<p>This is class is for current or aspiring content managers, strategists, bloggers and entrepreneurs. It will teach you how to create an emotional connection with your followers and gain buy-in from your core stakeholders.</p> <p>You will walk away with actionable steps to achieve organic, high-quality growth and engagement with your audience. Contrary to popular belief, you don't have to be a black hat SEO expert or a social media master to build a strong following.</p> <p>Use content as a powerful strategic tool for marketing, customer acquisition, relationship building, and new business development.</p> ",
        how_to_find_us:
          'Red line at State and Grand.  1 block north and 1 block west of us.  (3 minute walk)\nBlue, Purple, Green, Pink/Brown, Orange lines at Clark & Lake (10 minute walk)',
        visibility: 'public',
      },
      {
        created: 1553125962000,
        duration: 10800000,
        id: '259942144',
        name: 'Social Media Strategy Mapping ($60.00) ',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1559257200000,
        local_date: '2019-05-30',
        local_time: '18:00',
        updated: 1553125962000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 1,
        venue: {
          id: 25917182,
          name: 'General Assembly @ rent24',
          lat: 41.890647888183594,
          lon: -87.62683868408203,
          repinned: false,
          address_1: '444 N. Wabash Avenue, 5th Floor',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60611',
          state: 'il',
        },
        group: {
          created: 1413252782000,
          name: 'Chicago Startup Community',
          id: 17606542,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'Chicago-Startup-Community',
          who: 'Creators',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Startup-Community/events/259942144/',
        description:
          '<p>Social media initiatives don’t start when you register a Facebook or Twitter account and start posting announcements, it begins much sooner. In this workshop, you’ll be taken through a 6-step methodology that will help guide your efforts to develop an actionable social media strategy. You’ll learn how to structure your social media efforts, deploy your resources, and ultimately launch a social media campaign that is professional and provides results you’ll be able to interpret and understand.</p> ',
        how_to_find_us:
          'Red line at State and Grand.  1 block north and 1 block west of us.  (3 minute walk)\nBlue, Purple, Green, Pink/Brown, Orange lines at Clark & Lake (10 minute walk)',
        visibility: 'public',
      },
      {
        created: 1553126151000,
        duration: 25200000,
        id: '259942228',
        name: 'Code in One Day: HTML & CSS Crash Course ($195.00)',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1559314800000,
        local_date: '2019-05-31',
        local_time: '10:00',
        updated: 1553126151000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 2,
        venue: {
          id: 25917182,
          name: 'General Assembly @ rent24',
          lat: 41.890647888183594,
          lon: -87.62683868408203,
          repinned: false,
          address_1: '444 N. Wabash Avenue, 5th Floor',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60611',
          state: 'il',
        },
        group: {
          created: 1413252782000,
          name: 'Chicago Startup Community',
          id: 17606542,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'Chicago-Startup-Community',
          who: 'Creators',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Startup-Community/events/259942228/',
        description:
          "<p>HTML and CSS are the fundamental building blocks of the web. Whether you're a beginner who wants to get started in web development, a designer looking to hand-code their concepts, or a marketer who wants a little more control over their CMS, you'll need to know HTML and CSS to get the job done.</p> <p>This one day workshop is the quickest way to get started building websites. You will dive head first into HTML and CSS, skill up with live coding exercises, and by the end of the day you'll have a working web page to call your own.</p> ",
        how_to_find_us:
          'Red line at State and Grand.  1 block north and 1 block west of us.  (3 minute walk)\nBlue, Purple, Green, Pink/Brown, Orange lines at Clark & Lake (10 minute walk)',
        visibility: 'public',
      },
      {
        created: 1553126551000,
        duration: 21600000,
        id: '259942320',
        name: 'Project Management Bootcamp ($175.00) ',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1559401200000,
        local_date: '2019-06-01',
        local_time: '10:00',
        updated: 1553126551000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 2,
        venue: {
          id: 25917182,
          name: 'General Assembly @ rent24',
          lat: 41.890647888183594,
          lon: -87.62683868408203,
          repinned: false,
          address_1: '444 N. Wabash Avenue, 5th Floor',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60611',
          state: 'il',
        },
        group: {
          created: 1413252782000,
          name: 'Chicago Startup Community',
          id: 17606542,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'Chicago-Startup-Community',
          who: 'Creators',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Startup-Community/events/259942320/',
        description:
          '<p>Whether you’re a designer, a developer, or an entrepreneur who’s looking to get your own company off the ground, knowing how to effectively lead a team and complete a project is an essential element of success.</p> <p>This Bootcamp reviews the fundamentals of project management. It’s a good place to start whether you’ve found yourself taking on a pm role in your organization or are looking to transition to a career in the field.</p> <p>In this workshop, you’ll get an introduction to project management processes and best practices for interacting with the client, stakeholders and your team. Working with real world examples, you’ll gain the tools and resources that you’ll need to increase focus and improve your team’s productivity.</p> ',
        how_to_find_us:
          'Red line at State and Grand.  1 block north and 1 block west of us.  (3 minute walk)\nBlue, Purple, Green, Pink/Brown, Orange lines at Clark & Lake (10 minute walk)',
        visibility: 'public',
      },
      {
        created: 1553128822000,
        duration: 7200000,
        id: '259943570',
        name: 'LinkedIn & Resume Refresh For Career Changers ($35.00) ',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1559602800000,
        local_date: '2019-06-03',
        local_time: '18:00',
        updated: 1553128835000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 1,
        venue: {
          id: 25917182,
          name: 'General Assembly @ rent24',
          lat: 41.890647888183594,
          lon: -87.62683868408203,
          repinned: false,
          address_1: '444 N. Wabash Avenue, 5th Floor',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60611',
          state: 'il',
        },
        group: {
          created: 1413252782000,
          name: 'Chicago Startup Community',
          id: 17606542,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'Chicago-Startup-Community',
          who: 'Creators',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Startup-Community/events/259943570/',
        description:
          "<p>A strategically targeted resume is your most important weapon when searching for a job. This document is often the first impression that you will make with an employer. On average, employers initially look at resumes for 10–20 seconds, so you've got to knock 'em out with a great document. Students will leave this workshop knowing just how to do that.</p> <p>LinkedIn is the world’s professional social network and a vital resource to find business opportunities and form strategic alliances. We will explore LinkedIn’s unique feature-set and delve deep into the tools and techniques that will help you master LinkedIn. We will also walk through real examples of successful LinkedIn user profiles and learn the techniques to achieve an all-star profile.</p> ",
        how_to_find_us:
          'Red line at State and Grand.  1 block north and 1 block west of us.  (3 minute walk)\nBlue, Purple, Green, Pink/Brown, Orange lines at Clark & Lake (10 minute walk)\nMessage Input\nDirect message with gabriela.guevara',
        visibility: 'public',
      },
      {
        created: 1553128963000,
        duration: 7200000,
        id: '259943834',
        name: 'SQL For Beginners ( $45.00) ',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1559775600000,
        local_date: '2019-06-05',
        local_time: '18:00',
        updated: 1555165469000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 2,
        venue: {
          id: 25917182,
          name: 'General Assembly @ rent24',
          lat: 41.890647888183594,
          lon: -87.62683868408203,
          repinned: true,
          address_1: '444 N. Wabash Avenue, 5th Floor',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60611',
          state: 'il',
        },
        group: {
          created: 1413252782000,
          name: 'Chicago Startup Community',
          id: 17606542,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'Chicago-Startup-Community',
          who: 'Creators',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Startup-Community/events/259943834/',
        description:
          '<p>Looking to learn some basic SQL skills to filter, aggregate or produce reports from a database? Exporting data and using Excel instead of taking advantage of functionality your database already gives you? This class will give you the skills required to perform both basic and complex data manipulations with ease.</p> <p>This class will introduce students to SQL queries for data gathering and data analysis. We will cover enough query syntax and examples and hands on practice to get students started on querying a database and performing common data analysis tasks that are transferable to their own needs.</p> ',
        how_to_find_us:
          'Red line at State and Grand.  1 block north and 1 block west of us.  (3 minute walk)\nBlue, Purple, Green, Pink/Brown, Orange lines at Clark & Lake (10 minute walk)\n\nMessage Input\nDirect message with gabriela.guevara',
        visibility: 'public',
      },
      {
        created: 1553129272000,
        duration: 10800000,
        id: '259944422',
        name: 'Project Management Essentials ($60.00)',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1560294000000,
        local_date: '2019-06-11',
        local_time: '18:00',
        updated: 1553129296000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 1,
        venue: {
          id: 25917182,
          name: 'General Assembly @ rent24',
          lat: 41.890647888183594,
          lon: -87.62683868408203,
          repinned: false,
          address_1: '444 N. Wabash Avenue, 5th Floor',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60611',
          state: 'il',
        },
        group: {
          created: 1413252782000,
          name: 'Chicago Startup Community',
          id: 17606542,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'Chicago-Startup-Community',
          who: 'Creators',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Startup-Community/events/259944422/',
        description:
          "<p>If you're interested in becoming a project manager or simply want a more effective way to streamline and achieve your project goals, then this class is for you! We'll cover the fundamentals of project management, dissecting the differences between waterfall &amp; agile project management. We'll then take a deeper dive into agile project management, highlighting best practices for proper planning and execution. By the end of the class, you'll be equipped with the techniques and know-how to manage multiple project priorities with ease and efficiency.</p> ",
        how_to_find_us:
          'Red line at State and Grand.  1 block north and 1 block west of us.  (3 minute walk)\nBlue, Purple, Green, Pink/Brown, Orange lines at Clark & Lake (10 minute walk)\nMessage Input\nDirect message with gabriela.guevara',
        visibility: 'public',
      },
      {
        created: 1553129961000,
        duration: 9000000,
        id: '259944703',
        name: 'SEO for Beginners Workshop ($45.00) ',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1560466800000,
        local_date: '2019-06-13',
        local_time: '18:00',
        updated: 1553129961000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 1,
        venue: {
          id: 25917182,
          name: 'General Assembly @ rent24',
          lat: 41.890647888183594,
          lon: -87.62683868408203,
          repinned: false,
          address_1: '444 N. Wabash Avenue, 5th Floor',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60611',
          state: 'il',
        },
        group: {
          created: 1413252782000,
          name: 'Chicago Startup Community',
          id: 17606542,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'Chicago-Startup-Community',
          who: 'Creators',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Startup-Community/events/259944703/',
        description:
          '<p>Search engine optimization (SEO) is about improving the visibility of a website in “organic” (non-paid) search engine results. This no nonsense introduction will pull back the veil and unmask this mysterious thing called SEO, helping you to understand and start using it. You will be able to start improving your website’s rankings in the search engines.</p> <p>You’ll learn why your website needs SEO, what are the most important things you need to be doing to improve your SEO, the basics of how to do those things, and what the future holds for SEO.</p> <p>Taught by a professional SEO, he’ll share with you the secrets and tools the professionals use. Whether you already have a website or not, this course will give you the basic understanding you need to start driving customers with search engine optimization.</p> ',
        how_to_find_us:
          'Red line at State and Grand.  1 block north and 1 block west of us.  (3 minute walk)\nBlue, Purple, Green, Pink/Brown, Orange lines at Clark & Lake (10 minute walk)\n\nMessage Input\nDirect message with gabriela.guevara',
        visibility: 'public',
      },
      {
        created: 1553130349000,
        duration: 25200000,
        id: '259944808',
        name: 'Getting Started With Wordpress ($195.00) ',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1561215600000,
        local_date: '2019-06-22',
        local_time: '10:00',
        updated: 1555532306000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 1,
        venue: {
          id: 25917182,
          name: 'General Assembly @ rent24',
          lat: 41.890647888183594,
          lon: -87.62683868408203,
          repinned: true,
          address_1: '444 N. Wabash Avenue, 5th Floor',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60611',
          state: 'il',
        },
        group: {
          created: 1413252782000,
          name: 'Chicago Startup Community',
          id: 17606542,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'Chicago-Startup-Community',
          who: 'Creators',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Startup-Community/events/259944808/',
        description:
          '<p>WordPress is the premier content management system for those seeking an easy, user-friendly way to set up and maintain a website. In this class, you’ll walk through the basics of getting your site live quickly and discover various free templates as well as premium resources that require little to no coding skills and will have your site looking polished and professional. Once your site has gone live, you’ll learn how to update and maintain it using the WordPress dashboard, as well as common problems and pitfalls to avoid. Plus you’ll find out how to customize your site to get the exact look you’re going for.</p> ',
        how_to_find_us:
          'Red line at State and Grand.  1 block north and 1 block west of us.  (3 minute walk)\nBlue, Purple, Green, Pink/Brown, Orange lines at Clark & Lake (10 minute walk)\n\nMessage Input\nDirect message with gabriela.guevara\nStar this direct message',
        visibility: 'public',
      },
      {
        created: 1553130663000,
        duration: 7200000,
        id: '259944871',
        name: 'Data Analytics With Tableau ($40.00) ',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1560812400000,
        local_date: '2019-06-17',
        local_time: '18:00',
        updated: 1553130663000,
        utc_offset: -18000000,
        waitlist_count: 0,
        yes_rsvp_count: 2,
        venue: {
          id: 25917182,
          name: 'General Assembly @ rent24',
          lat: 41.890647888183594,
          lon: -87.62683868408203,
          repinned: false,
          address_1: '444 N. Wabash Avenue, 5th Floor',
          city: 'Chicago',
          country: 'us',
          localized_country_name: 'USA',
          zip: '60611',
          state: 'il',
        },
        group: {
          created: 1413252782000,
          name: 'Chicago Startup Community',
          id: 17606542,
          join_mode: 'open',
          lat: 41.88999938964844,
          lon: -87.63999938964844,
          urlname: 'Chicago-Startup-Community',
          who: 'Creators',
          localized_location: 'Chicago, IL',
          state: 'IL',
          country: 'us',
          region: 'en_US',
          timezone: 'US/Central',
        },
        link:
          'https://www.meetup.com/Chicago-Startup-Community/events/259944871/',
        description:
          '<p>Data analytics is in the midst of an evolution. In today’s digital world, the practice of decision makers relying on information to be delivered to them is no longer sufficient to keep pace. Tableau is software that puts access to data, and the insights it can unlock, directly in the hands of those who need it.</p> <p>Tableu is designed to help people see and understand data and offers a powerful yet intuitive and easy to use method of visually exploring &amp; analyzing data for more effective decision making and strategizing.</p> <p>This workshop provides an introduction to visual data discovery using Tableau software. It will explore how to use Tableau to connect to, interpret, and analyze data. You will explore sample data sets and then create a Tableau Dashboard showcasing the insights they have discovered.</p> ',
        how_to_find_us:
          'Red line at State and Grand.  1 block north and 1 block west of us.  (3 minute walk)\nBlue, Purple, Green, Pink/Brown, Orange lines at Clark & Lake (10 minute walk)\nMessage Input\nDirect message with gabriela.guevara\nStar this direct message',
        visibility: 'public',
      },
    ],
    ratelimit: { limit: '30', remaining: '29', reset: '10' },
  },
}

const meetupResultSet = offset => {
  const nextMonth = DateTime.local()
    .setZone('America/Chicago')
    .plus({ months: 1 })
    .set({ day: 1, hour: 5, minute: 0 })
  const year = nextMonth.year
  const month = nextMonth.month
  let data = MEETUP_RESULTS
  for (let i = 0; i < data.response.events.length; i++) {
    const eventTime = nextMonth.plus({ days: i })
    data.response.events[i].time = eventTime.valueOf()
    data.response.events[i].local_date = eventTime.toISODate()
    data.response.events[i].local_time = eventTime.toFormat('HH:mm')
  }
  return data
}

module.exports = {
  getValidEventData: () => ({
    eventName: 'Test Event',
    description: 'This is not a real event. It is just for testing',
    linkURL: 'https://eventbrite.com/test-event',
    cost: 'FREE',
    locationName: '1871 Chicago',
    locationStreet: '222 W Merchandise Mart Plaza #1212',
    locationCity: 'Chicago',
    authorName: 'Joe Tester',
    startDate: defaultEventDate(),
    startTime: '5:00pm',
    endDate: defaultEventDate(),
    endTime: '7:00pm',
  }),
  getDefaultEventDate: () => {
    return defaultEventDate()
  },
  getMeetupResults: offset => {
    return meetupResultSet(offset)
  },
  deferred: () => {
    const deferred = {}
    deferred.promise = new Promise((resolve, reject) => {
      deferred.resolve = resolve
      deferred.reject = reject
    })
    return deferred
  },
}
